[package]
name = "path-tree"
version = "0.0.4"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "Path-based routing tree"
repository = "https://github.com/trek-rs/path-tree"
documentation = "https://github.com/trek-rs/path-tree/"
readme = "README.md"
keywords = ["radix", "tree", "path", "router"]
license = "MIT/Apache-2.0"

[lib]
bench = false

[dependencies]
radix-tree = "^0.0"

[dev-dependencies]
actix-router = { git="https://github.com/actix/actix-net", path="router" }
path-table = "^1.0"
route-recognizer = "^0.1"
criterion = "^0.2"

[[bench]]
name = "routers"
harness = false
