[package]
name = "path-tree"
version = "0.1.9"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "path-tree is a lightweight high performance HTTP request router for Rust"
repository = "https://github.com/trek-rs/path-tree"
documentation = "https://github.com/trek-rs/path-tree/"
readme = "README.md"
keywords = ["radix", "tree", "path", "router"]
license = "MIT/Apache-2.0"

include = [
    "src/*.rs",
    "Cargo.toml",
    "CHANGES.md",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[lib]
bench = false

[dev-dependencies]
actix-router = "0.2"
path-table = "1.0"
route-recognizer = "0.2"
criterion = "0.2"
hyper = "0.13"
futures = "0.3"
rand = "0.7.3"
tokio = { version = "0.2", default-features = false, features = ["macros"] }

[[bench]]
name = "routers"
harness = false
path = "benches/routers.rs"

[[example]]
name = "hello"
path = "examples/hello.rs"

[[test]]
name = "basic"
path = "tests/basic.rs"

[[test]]
name = "github"
path = "tests/github.rs"
