[package]
name = "path-tree"
version = "0.1.9"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "path-tree is a lightweight high performance HTTP request router for Rust"
repository = "https://github.com/trek-rs/path-tree"
documentation = "https://github.com/trek-rs/path-tree/"
readme = "README.md"
keywords = ["radix", "tree", "path", "router"]
license = "MIT/Apache-2.0"

include = [
    "src",
    "Cargo.toml",
    "CHANGES.md",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[lib]
bench = false

[dev-dependencies]
actix-router = "^0.1"
path-table = "^1.0"
route-recognizer = "^0.1"
criterion = "^0.2"
hyper = { version = "0.13.0-alpha.4", features = ["unstable-stream"] }
futures-preview = "=0.3.0-alpha.19"
tokio = { version = "0.2.0-alpha.6", default-features = false, features = ["rt-full"] }

[[bench]]
name = "routers"
harness = false

[[example]]
name = "hello"
path = "examples/hello.rs"

[[test]]
name = "basic"
path = "tests/basic.rs"

[[test]]
name = "github"
path = "tests/github.rs"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
