[package]
name = "path-tree"
version = "0.0.1"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "Path-based routing tree"
repository = "https://github.com/trek-rs/path-tree"
documentation = "https://github.com/trek-rs/path-tree/"
readme = "README.md"
keywords = ["radix", "tree", "path", "router"]
license = "MIT/Apache-2.0"

[dependencies]
radix-tree = "^0.0"
